### ISSUE TITLE
Build a Drum Machine certification project

### ISSUE THREAD

**Issue by SimonaPiz** [SimonaPiz/Drum-Machine#2]
[front-end-development-libraries](https://www.freecodecamp.org/learn/front-end-development-libraries/front-end-development-libraries-projects/build-a-drum-machine)

**Objective:** Build an app that is functionally similar to this: https://drum-machine.freecodecamp.rocks/.

<img src="https://github.com/SimonaPiz/Drum-Machine/assets/91121660/3a941119-2d87-4349-9947-a8f21b1284f4" width="400px" alt="drum-machine-preview" title="drum-machine-preview">

Fulfill the below user stories and get all of the tests to pass. Use whichever libraries or APIs you need. Give it your own personal style.

### User Stories:

- [x]  I should be able to see an outer container with a corresponding `id="drum-machine"` that contains all other elements. #1 
- [x]  Within `#drum-machine` I can see an element with a corresponding `id="display"`. #1
- [x]  Within `#drum-machine` I can see 9 clickable drum pad elements, each with a class name of `drum-pad`, a unique id that describes the audio clip the drum pad will be set up to trigger, and an inner text that corresponds to one of the following keys on the keyboard: `Q`, `W`, `E`, `A`, `S`, `D`, `Z`, `X`, `C`. The drum pads MUST be in this order. #1 
- [x]  Within each `.drum-pad`, there should be an HTML5 `audio` element which has a `src` attribute pointing to an audio clip, a class name of `clip`, and an id corresponding to the inner text of its parent `.drum-pad` (e.g. `id="Q"`, `id="W"`, `id="E"` etc.). #1 
- [x]  When I click on a `.drum-pad` element, the audio clip contained in its child `audio` element should be triggered. #4 
- [x]  When I press the trigger key associated with each `.drum-pad`, the audio clip contained in its child `audio` element should be triggered (e.g. pressing the `Q` key should trigger the drum pad which contains the string `Q`, pressing the `W` key should trigger the drum pad which contains the string `W`, etc.). #4 
- [x]  When a `.drum-pad` is triggered, a string describing the associated audio clip is displayed as the inner text of the `#display` element (each string must be unique). #4
